### ISSUE TITLE
rear suspension

### ISSUE THREAD

**Issue by axelav** [axelav/XL600R#3]
rear suspension is covered in what must be years of dirt & oil. needs to be cleaned, inspected & greased.

### parts

- [x] swing arm bolt cap http://www.bikebandit.com/oem-parts/1983-honda-xl600r/o/m9699#sch421936

- [x] front chain rub block https://www.dcvmx.com/xcart/product.php?productid=184050&cat=1018&page=1
- [x] front chain slider https://www.dcvmx.com/xcart/product.php?productid=184020&cat=1018&page=1

### todo

- [x] grease all bearings/caps
- [x] install front chain slider

**Comment by axelav** [comment]
had to drill into the spring to swing arm bolt cuz I stripped the net torquing it...might've read the wrong value. ordered new bolt & nut. may need to repack the linkage bearings & dust caps tho.

- [ ] regrease linkage bearings/caps

**Comment by axelav** [comment]
rear suspension back on!

![fullsizerender](https://cloud.githubusercontent.com/assets/59404/6385044/c60ea578-bd32-11e4-95bb-9d075e83c656.jpg)

**Comment by axelav** [comment]
bring everything into test until I've brought the bike outside, sat on it, etc.

**Comment by axelav** [comment]
- [ ] install front chain slider

collars & screws are on the way...
